spring:
  application:
    name: employee_api
  datasource:
    url: jdbc:postgresql://localhost:5432/employee
    username: employee_user
    password: employee_password
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9092
    topic: EmployeeTopic
server:
  port: 8080
  compression:
    enabled: true
  error:
    include-message: always
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method